collection_name: agent
persist_directory: chroma_db
k: 3
data_path: data
md5_hex_store: md5.text
allow_knowledge_file_type: ["txt","pdf"]
chunk_size: 500
chunk_overlap: 20
separators: ['.', '?', '!', '。', '？', '！', ';', '；','\n\n']
api_key: os.environ.get("API_KEY")
api_base: "https://api.siliconflow.cn/v1/"
embedding_model_name: "Qwen/Qwen3-Embedding-0.6B"
chat_model_name: "deepseek-ai/DeepSeek-V3.2"



